# DiscordLink Config

# The discord token.
discordToken="TOKEN"

# The id of the channel you want messages to sync with.
channelID="CHANNEL_ID"

# Set this to true to use 2d avatars as discord profile pictures
# instead of the default 3d ones.
use2dAvatars=false

# Sets the format of messages sent from discord to minecraft
# formatted with minimessage - https://docs.adventure.kyori.net/minimessage.html#format
# Placholders:
# %displayname% - discord display name (includes nicknames)
# %username% - discord username (does not include nicknames)
# %message% - the message sent in discord
messageFormat="<rainbow>[Discord]</rainbow> %displayname% >> %message%"

# This allows people to ping discord users from within minecraft
# This only applys to individual users, not roles or @everyone
allowUserPings = true

# Don't touch this
configVersion=1
