# DiscordLink Config

# Enable Proxy support (bungeecord/velocity). This should only be used on Spigot servers
# when behind a Proxy. By enabling this, you can ignore the rest of the settings here,
# as you will set them in your proxies DiscordLink config.
proxy=false

# The discord token.
discordToken="TOKEN"

# The id of the channel you want messages to sync with.
channelID="CHANNEL_ID"

# Set this to true to use 2d avatars as discord profile pictures
# instead of the default 3d ones.
use2dAvatars=false

# Sets the format of messages sent from discord to minecraft
# formatted with minimessage - https://docs.adventure.kyori.net/minimessage.html#format
# Placholders:
# %displayname% - discord display name (includes nicknames)
# %username% - discord username (does not include nicknames)
# %message% - the message sent in discord
messageFormat="<rainbow>[Discord]</rainbow> %displayname% >> %message%"

# Don't touch this
configVersion=1
